Household.destroy_all
Guest.destroy_all
Order.destroy_all
Photo.destroy_all

@alvarez=Household.create!(surname:'Alvarez', guest_count:2, address1:'304 Park St', address2:'', city:'Clover', state:'SC', zip:29710, country:'US')
@assam=Household.create!(surname:'Assam', guest_count:2, address1:'2 Main Rd', address2:'', city:'Glendale', state:'AZ', zip:85303, country:'US')
@beckam=Household.create!(surname:'Beckam', guest_count:3, address1:'44 Coopers Road', address2:'Apt 204', city:'Pheonix', state:'AZ', zip:85003, country:'US')
@giordana=Household.create!(surname:'Giordana', guest_count:3, address1:'32-32 102th St', address2:'Apt 2011', city:'Kew Gardens', state:'NY', zip:11415, country:'US')
@johnson=Household.create!(surname:'Johnson', guest_count:4, address1:'401 Uphill Rd', address2:'', city:'San Francisco', state:'CA', zip:94102, country:'US')
@leed=Household.create!(surname:'Leed', guest_count:2, address1:'402 Sheldon Creek', address2:'', city:'Albuquerque ', state:'NM', zip:87102, country:'US')
@liu=Household.create!(surname:'Liu', guest_count:2, address1:'199 Radiant Creek Rd', address2:'', city:'Austin', state:'TX', zip:78748, country:'US')
@mirelda=Household.create!(surname:'Mirelda', guest_count:2, address1:'301 Park Rd', address2:'', city:'Seattle', state:'WA', zip:98101, country:'US')
@wakamatsu=Household.create!(surname:'Wakamatsu', guest_count:3, address1:'219 Walter Ave', address2:'Apt 2A', city:'Portland', state:'ME', zip:04101, country:'US')

Guest.create!([{first_name:'Bob', surname:'Alvarez', attending:true, under10:false, phone:222222222, email:'hling@comcast.net', household:@alvarez}, {first_name:'Jasmine', surname:'Assam', attending:true, under10:false, phone:5553923933, email:'jimxugle@yahoo.com', household:@assam}, {first_name:'Monique', surname:'Beckam', attending:true, under10:false, phone:5550339933, email:'fatelk@msn.com', household:@beckam}, {first_name:'Wendy', surname:'Giordana', attending:true, under10:false, phone:5552939444, email:'starstuff@outlook.com', household:@giordana}, {first_name:'Mike', surname:'Johnson', attending:false, under10:false, phone:5550033320, email:'webdragon@gmail.com', household:@johnson}, {first_name:'Frank', surname:'Leed', attending:true, under10:false, phone:5592933933, email:'chrwin@msn.com', household:@leed}, {first_name:'Jason', surname:'Liu', attending:true, under10:false, phone:5503929333, email:'lamprecht@hotmail.com', household:@liu}, {first_name:'Jake', surname:'Mirelda', attending:false, under10:false, phone:5529339444, email:'scato@me.com', household:@mirelda}, {first_name:'Taka', surname:'Wakamatsu', attending:true, under10:false, phone:5552033320, email:'mcsporran@comcast.net', household:@wakamatsu}, {first_name:'Suzy', surname:'Alvarez', attending:true, under10:false, phone:5559393933, email:'netsfr@hotmail.com', household:@alvarez}, {first_name:'Shelly', surname:'Beckam', attending:true, under10:false, phone:5553929333, email:'tmccarth@sbcglobal.net', household:@beckam}, {first_name:'Jennifer', surname:'Giordana', attending:true, under10:false, phone:5535293944, email:'improv@comcast.net', household:@giordana}, {first_name:'Belen', surname:'Johnson', attending:false, under10:false, phone:5550303320, email:'hling@comcast.net', household:@johnson}, {first_name:'Mary', surname:'Leed', attending:true, under10:false, phone:5559933933, email:'jimxugle@yahoo.com', household:@leed}, {first_name:'Lila', surname:'Mirelda', attending:true, under10:false, phone:5550323933, email:'fatelk@msn.com', household:@mirelda}, {first_name:'Lena', surname:'Wakamatsu', attending:true, under10:false, phone:5552393944, email:'starstuff@gmail.com', household:@wakamatsu}, {first_name:'Tim', surname:'Beckam', attending:true, under10:true, phone:nil, email:'', household:@beckam}, {first_name:'Mary', surname:'Giordana', attending:false, under10:true, phone:nil, email:'', household:@giordana}, {first_name:'Tina', surname:'Johnson', attending:true, under10:true, phone:nil, email:'', household:@johnson}, {first_name:'Anju', surname:'Wakamatsu', attending:true, under10:true, phone:nil, email:'', household:@wakamatsu}, {first_name:'Gregory', surname:'Johnson', attending:false, under10:true, phone:nil, email:'', household:@johnson}])